---
title: "Exercise 5.4: Hypothesis testing on the shrimps dataset"
author: "Lieven Clement, Jeroen Gilis and Milan Malfait"
date: "statOmics, Ghent University (https://statomics.github.io)"
---

# Aims of this exercise

This exercise aims to further sharpen your skills in

- translating the research question in a a null and alternative hypothesis of t-tests
- critically evaluating the assumptions of t-tests, and 
- selecting the appropriate test for answering the research question. 

# The shrimps dataset

Dataset on the accumulation of PCBs (Polychlorinated biphenyls)
in the adipose tissue of shrimps. PCBs are often present in coolants, and are
know to accumulate easily in the adipose tissue of shrimps. In this experiment,
two groups of 18 samples (each 100 grams) of shrimps each were cultivated
in different conditions, one control condition and one condition
where the medium was poluted with PCBs. Note that the PCB concentrations were
measured in pg/g adipose tissue.

# Research question

Is there an effect of the
growth condition on the PCB concentration in the adipose
tissue of shrimps?

# Exercises and questions

1. Explore the data what do you observe?

  Data path: `https://raw.githubusercontent.com/statOmics/PSLS21/data/shrimps.txt`

2. How will you model the data?

3. Translate the research question in a null and alternative hypothesis

4. Which test will you use to assess the research hypothesis?

5. Formulate the assumptions of the test and assess the assumptions using
diagnostic plots.

6. If all assumptions to perform the test are met, complete the analysis and
formulate a proper conclusion.
