---
title: "Exercises on chapter 9: Non-parametric statistics"
author: "Lieven Clement and Jeroen Gilis"
date: "statOmics, Ghent University (https://statomics.github.io)"
---

On the second/third day of the "Practical Statistics for the Life Sciences" course, we will have one exercise on non-parametric analysis for two groups and one exercise for non-parametric analysis for multiple groups.

# The shrimps dataset

Dataset on the accumulation of PCBs (Polychlorinated biphenyls)
in the adipose tissue of shrimps. PCBs are often present in coolants, and are
know to accumulate easily in the adipose tissue of shrimps. In this experiment,
two groups of 18 samples (each 100 grams) of shrimps each were cultivated
in different conditions, one control condition and one condition
where the medium was poluted with PCBs.

The research question is; is there an effect of the growth condition on the PCB
concentration in the adipose tissue of shrimps?

- Exercise: [Exercise1](./09_1_shrimps.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/shrimps.txt
<!-- - Solution: [Solution1](./09_1_shrimps_sol.html) -->

---

# The lettuce freshweight dataset

In agriculture, it is important to have a high yield of crops. One way to
increase the number of leaves (or better, total leaf weight) is by using a
fertilizer.

Here, we consider three types of fertilizers:

  - biochar
  - compost
  - cobc (combination of biochar and compost)

The researchers want to find out if either of these fertilizers have a positive
influence on the growth of lettuce plants. To this end, they grew up lettuce
plants in a greenhouse. The pots were filled with one of four soil types;

  - Soil only (control)
  - Soil supplemented with biochar (refoak)
  - Soil supplemented with compost (compost)
  - Soil supplemented with both biochar and compost (cobc)

The dataset `freshweight_lettuce.txt` contains the freshweight for 28 lettuce
plants. The researchers want to test if there is an effect of one or more of
the treatments on the growth of lettuce plants.

- Exercise: [Exercise2](./09_2_lettuce.html)
- Data path: https://raw.githubusercontent.com/statOmics/PSLS21/data/freshweight_lettuce.txt
<!-- - Solution: [Solution2](./09_2_lettuce_sol.html) -->

---
